### ISSUE TITLE
Error: Must call suspend() before calling throw() after QueueState destroyed 

### ISSUE THREAD

**Issue by EdmondDantes** [amphp/pipeline#22]
Precondition:
1. Create Queue();
2. Create DeferredCancellation();
3. call $cancellation->cancel();
4. call $queue->complete();

Result for some conditions: **Must call suspend() before calling throw()**

Reason by logical level: It's possible that there is a design limitation on calling the complete() method in another fiber. I didn't notice these limitations. If they indeed exist, they should be documented.

Reason for code: 
Class QueueState
```
        if ($cancellation) {
            $waiting = &$this->waiting; <==== Look here!!!
            $offset = &$this->positionOffset;
            $id = $cancellation->subscribe(static function (\Throwable $exception) use (
                &$waiting, 
                &$offset,
                $suspension,
            ): void {
                foreach ($waiting as $key => $pending) {
                    if ($pending === $suspension) {
                        unset($waiting[$key]);
                        ++$offset;
                        $suspension->throw($exception);
                        return;
                    }
                }
            });
        }

```

and bug here:
```
    private function resolvePending(): void
    {
        $waiting = $this->waiting;
        unset($this->waiting); // <== maybe bug here 

```

Since $cancellation->cancel(); is called asynchronously under the hood, the queue object can be completely destroyed in memory before the callback is invoked. In fact, we don't even know exactly when it will be destroyed. Due to the fact that the waiting class property is destroyed via unset, the expression with the reference remains unchanged. 

I use fix
```
        $waiting = $this->waiting;
        $this->waiting = [];
        unset($this->waiting);
```

From the code, it's evident that this is not a bug but rather intentional. However, in this case, there is still an error in that the order of object destruction and callback invocation is undefined, and this should be somehow accounted for in the code.

PS. Thanks for your hard work.

**Comment by trowski** [comment]
Thanks for reporting this issue! This was not intentional, `unset($this->waiting)` was a mistake since it did not clear the array in the reference used in the cancellation callback. Simply changing it to `$this->waiting = []` fixed the issue.
